/**
 * Setup command - Install Markform as a Claude Code skill.
 *
 * Copies SKILL.md to .claude/skills/markform/ in the current project.
 * Supports --auto (non-interactive, for agents) and --interactive (guided, for humans).
 */

import type { Command } from 'commander';

import { existsSync, readFileSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import * as p from '@clack/prompts';
import pc from 'picocolors';

import type { CommandContext } from '../lib/cliTypes.js';
import { resolvePackagePath } from '../lib/paths.js';
import { getCommandContext, logError, logInfo, logSuccess } from '../lib/shared.js';

const DO_NOT_EDIT_MARKER = `<!-- DO NOT EDIT: Generated by markform setup.
Run 'markform setup' to update.
-->`;

/**
 * Load SKILL.md content and insert the DO NOT EDIT marker after frontmatter.
 */
function loadSkillWithMarker(): string {
  const skillPath = resolvePackagePath(import.meta.url, 'docs/skill/SKILL.md');
  const content = readFileSync(skillPath, 'utf-8');

  // Insert "DO NOT EDIT" marker after YAML frontmatter
  const lines = content.split('\n');
  let endOfFrontmatter = -1;
  if (lines[0] === '---') {
    for (let i = 1; i < lines.length; i++) {
      if (lines[i] === '---') {
        endOfFrontmatter = i;
        break;
      }
    }
  }

  if (endOfFrontmatter >= 0) {
    lines.splice(endOfFrontmatter + 1, 0, '', DO_NOT_EDIT_MARKER);
  }

  return lines.join('\n');
}

/**
 * Install the skill file to .claude/skills/markform/SKILL.md.
 */
async function installSkill(projectDir: string, ctx: CommandContext): Promise<void> {
  const skillDir = join(projectDir, '.claude', 'skills', 'markform');
  const skillPath = join(skillDir, 'SKILL.md');

  const isUpdate = existsSync(skillPath);
  const content = loadSkillWithMarker();

  await mkdir(skillDir, { recursive: true });
  await writeFile(skillPath, content, 'utf-8');

  const verb = isUpdate ? 'Updated' : 'Installed';
  logSuccess(ctx, `${verb} ${pc.bold('.claude/skills/markform/SKILL.md')}`);
}

/**
 * Run setup in auto mode (non-interactive, for agents).
 */
async function setupAuto(ctx: CommandContext): Promise<void> {
  logInfo(ctx, 'Installing Markform skill for Claude Code...');
  await installSkill(process.cwd(), ctx);
  logInfo(ctx, `Run ${pc.cyan('markform skill')} to view the installed skill content.`);
}

/**
 * Run setup in interactive mode (guided, for humans).
 */
async function setupInteractive(ctx: CommandContext): Promise<void> {
  p.intro(pc.bgCyan(pc.black(' markform setup ')));

  p.log.info(
    [
      'This will install Markform as a Claude Code skill in your project.',
      '',
      `  ${pc.dim('Creates:')} .claude/skills/markform/SKILL.md`,
      '',
      'This teaches Claude Code how to use markform commands when working',
      'with .form.md files in this project.',
    ].join('\n'),
  );

  const shouldContinue = await p.confirm({
    message: 'Install the Markform skill?',
    initialValue: true,
  });

  if (p.isCancel(shouldContinue) || !shouldContinue) {
    p.outro('Setup cancelled.');
    return;
  }

  await installSkill(process.cwd(), ctx);

  p.outro('Markform skill installed! Claude Code will now know how to use markform.');
}

/**
 * Register the setup command.
 */
export function registerSetupCommand(program: Command): void {
  const cmd = program
    .command('setup')
    .description('Install Markform as a Claude Code skill in the current project')
    .option('--auto', 'Non-interactive setup (for agents and scripts)')
    .option('--interactive', 'Guided setup with prompts (for humans)')
    .action(async (options: { auto?: boolean; interactive?: boolean }, command: Command) => {
      const ctx = getCommandContext(command);

      try {
        if (!options.auto && !options.interactive) {
          // Default: show help if no mode flag
          cmd.help();
          return;
        }

        if (options.auto) {
          await setupAuto(ctx);
        } else {
          await setupInteractive(ctx);
        }
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        logError(message);
        process.exit(1);
      }
    });
}
